In [1]:
import numpy as np
import pandas as pd
import glob

In [2]:
df1 = pd.read_csv("202504-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df2 = pd.read_csv("202505-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df3 = pd.read_csv("202506-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df4 = pd.read_csv("202507-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df5 = pd.read_csv("202508-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df6 = pd.read_csv("202509-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df7 = pd.read_csv("202510-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df8 = pd.read_csv("202511-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df9 = pd.read_csv("202512-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df10 = pd.read_csv("202601-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df11 = pd.read_csv("202602-divvy-tripdata.csv", engine="python", on_bad_lines="skip")
df12 = pd.read_csv("202603-divvy-tripdata.csv", engine="python", on_bad_lines="skip")

In [3]:
df = pd.concat(
    [df1, df2, df3, df4, df5, df6,
     df7, df8, df9, df10, df11, df12],
    ignore_index=True
)

In [4]:
df.shape

(3390891, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3390891 entries, 0 to 3390890
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 336.3+ MB

In [6]:
df.columns.tolist()

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual']

In [7]:
df.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    660833
start_station_id      660833
end_station_name      624906
end_station_id        624906
start_lat                  0
start_lng                  0
end_lat                 2711
end_lng                 2711
member_casual              0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

In [10]:
df[['started_at', 'ended_at']].dtypes

started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [11]:
df['ride_length'] = (
    df['ended_at'] - df['started_at']
).dt.total_seconds() / 60

In [12]:
df['ride_length'].describe()

count    3.390891e+06
mean     1.508994e+01
std      5.110778e+01
min     -5.479480e+01
25%      5.174583e+00
50%      8.950667e+00
75%      1.569731e+01
max      1.559950e+03
Name: ride_length, dtype: float64

In [13]:
(df['ride_length'] > 60).sum()

63698

In [14]:
(df['ride_length'] > 1440).sum()

2704

In [15]:
(df['ride_length'] < 0).sum()

28

In [16]:
df = df[df['ride_length'] >0 ]

In [17]:
df = df[df['ride_length'] <= 1440]

In [18]:
df['day_of_week'] = df['started_at'].dt.day_name()

df['month'] = df['started_at'].dt.month_name()

df['hour'] = df['started_at'].dt.hour

In [20]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,month,hour
0,AF3863596DF9D94B,classic_bike,2025-04-27 14:29:34.619,2025-04-27 14:36:23.584,Troy St & Elston Ave,15631,Richmond St & Diversey Ave,15645,41.945244,-87.706650,41.931902,-87.701195,member,6.816083,Sunday,April,14
1,8B38081EBE918800,electric_bike,2025-04-23 17:48:51.863,2025-04-23 17:59:06.015,Wabash Ave & Adams St,KA1503000015,Green St & Madison St,TA1307000120,41.879472,-87.625689,41.881859,-87.649264,member,10.235867,Wednesday,April,17
2,1C7F1DE826BBBC8D,electric_bike,2025-04-05 17:55:30.845,2025-04-05 18:05:40.032,Damen Ave & Cortland St,13133,California Ave & Fletcher St,15642,41.915983,-87.677335,41.938429,-87.698008,member,10.153117,Saturday,April,17
3,CAD23D69A79A6C3B,classic_bike,2025-04-03 08:22:04.493,2025-04-03 08:32:06.099,Clark St & Elm St,TA1307000039,Orleans St & Merchandise Mart Plaza,TA1305000022,41.902973,-87.631280,41.888243,-87.636390,member,10.026767,Thursday,April,8
4,BE241E601482E0AB,electric_bike,2025-04-15 06:09:55.293,2025-04-15 06:19:58.942,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,41.898418,-87.686596,41.920082,-87.677855,member,10.060817,Tuesday,April,6

In [21]:
df[['ride_length','day_of_week','month','hour']].isnull().sum()

ride_length    0
day_of_week    0
month          0
hour           0
dtype: int64

In [24]:
df['member_casual'].value_counts()

member_casual
member    2306164
casual    1081995
Name: count, dtype: int64

In [25]:
(df['member_casual'].value_counts(normalize=True)*100).round(2)

member_casual
member    68.07
casual    31.93
Name: proportion, dtype: float64

In [27]:
df.groupby('member_casual')['ride_length'].mean()

member_casual
casual    18.519246
member    11.741672
Name: ride_length, dtype: float64

In [30]:
pd.crosstab(
    df['day_of_week'],
    df['member_casual']
)

member_casual  casual  member
day_of_week
Friday         172573  341944
Monday         128806  330564
Saturday       224932  286166
Sunday         173124  235098
Thursday       138711  372431
Tuesday        123395  377075
Wednesday      120454  362886

In [31]:
pd.crosstab(
    df['rideable_type'],
    df['member_casual']
)

member_casual  casual   member
rideable_type
classic_bike   366166   847329
electric_bike  715829  1458835

In [32]:
pd.crosstab(
    df['month'],
    df['member_casual']
)

member_casual  casual  member
month
April          108971  262096
August         145979  194543
December        28005  112415
February        41088  160251
January         24656  112933
July            81772  124701
June            81815  125376
March           87635  229128
May            182183  319720
November        88035  237697
October         98858  210027
September      112998  217277

In [33]:
df['month'].value_counts()

month
May          501903
April        371067
August       340522
September    330275
November     325732
March        316763
October      308885
June         207191
July         206473
February     201339
December     140420
January      137589
Name: count, dtype: int64

In [35]:
df.to_csv("cyclistic_cleaned_data.csv", index=False)

In [ ]:
df.describe().to_csv("summary_statistics.csv")